### PR TITLE
use latest vagrant and virtual box versions

### PR DESCRIPTION
**Pull request by adamsilverstein**
* Update vagrant and virtual box to latest versions as of 11/24/2017

### CODE REVIEW

**Comment by cfoellmann** [comment]
at least on windows I would suggest not moving on to Virtialbox 5.2.* and the newer vagrant versions didnt run on my machine. 
Could have been something else but maybe someone else can pitch in on this

**Comment by adamsilverstein** [comment]
Yea, would appreciate feedback on this. I'll build with the current versions for now.

**Comment by cfoellmann** [comment]
do you have a VB 5.3.* + Vagrant 2.0.1 running on Windows? That an some other combos were broken for me

**Comment by adamsilverstein** [comment]
I'm on mac, so i'll leave this as is for now until we get more feedback on the latest version from windows users.

**Comment by tomjn** [comment]
The latest of the 5.2.x branch of VBox should be fine, and make sure you're on VVV 2.1 not 2.0.1, it's got a huge amount of fixes

**Pull request merged**
